openapi: 3.0.3
info:
  title: OneOcean vessel tracking api
  description: Rest api used for getting vessel information.
  version: 0.0.1

servers:
  - url: https://127.0.0.1/api/

paths:
  /vessels:
    get:
      tags:
        - vessels
      summary: Returns a list of all the vessels IDs.
      responses:
        '200':    # status code
          description: A JSON array of all vessels IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /{vesselId}/averageSpeed:
    get:
      tags:
        - vessels
      summary: Returns the average speed of the selected vessel.
      parameters:
        - name: vesselId
          in: path
          required: true
          description: Id of the vessel to get info.
          schema:
            type: string
      responses:
        '200': # status code
          description: A JSON object with the requested info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: vessel1
                  averageSpeedKph:
                    type: number

  /{vesselId}/distanceTraveled:
    get:
      tags:
        - vessels
      summary: Returns distance traveled by the selected vessel.
      parameters:
        - name: vesselId
          in: path
          required: true
          description: Id of the vessel to get info.
          schema:
            type: string
      responses:
        '200': # status code
          description: A JSON object with the requested info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: vessel1
                  distanceTraveledKm:
                    type: number

  /{vesselId}/gpsTrack:
    get:
      tags:
        - vessels
      summary: Returns a list of gps points describing the path traveled traveled by the selected vessel.
      parameters:
        - name: vesselId
          in: path
          required: true
          description: Id of the vessel to get info.
          schema:
            type: string
      responses:
        '200': # status code
          description: A JSON array containing the gps locations of the selected vessel.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: vessel1
                  gpsTrack:
                    type: array
                    items:
                      type: object
                      properties:
                        xKm:
                          type: integer
                        yKm:
                          type: integer
                        timestamp:
                          type: string

  /alarms:
    get:
      tags:
        - vessels
      summary: Returns a list of all detected proximity alarms.
      responses:
        '200':    # status code
          description: An array of all detected proximity alarms.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    location:
                      type: object
                      properties:
                        xKm:
                          type: integer
                        yKm:
                          type: integer
                        timestamp:
                          type: string
                    vessels:
                      type: array
                      items:
                        type: string
                        example: vessel1
                    timestamp:
                      type: string
                      example: 2020-01-01T08:49:00Z
