openapi: 3.1.0
info:
  title: Vessel
  description: API for vessel information.
  version: 0.0.1
servers:
  - url: /api/

paths:
  /api/vessels:
    get:
      summary: Returns a list of all the vessels IDs.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/{vesselId}/averageSpeed:
    get:
      summary: Returns the average speed of the selected vessel.
      parameters:
        - name: vesselId
          in: path
          required: true
          description: Id of the vessel to get info.
          schema:
            type: string
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/{vesselId}/distanceTraveled:
    get:
      summary: Returns distance traveled by the selected vessel.
      parameters:
        - name: vesselId
          in: path
          required: true
          description: Id of the vessel to get info.
          schema:
            type: string
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/{vesselId}/gpsTrack:
    get:
      summary: Returns a list of gps points describing the path traveled traveled by the selected vessel.
      parameters:
        - name: vesselId
          in: path
          required: true
          description: Id of the vessel to get info.
          schema:
            type: string
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string